language: php

php:
  - '7.4'
  - '7.3'

script: echo "$(./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover tests/logs/clover.xml)"

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer require php-coveralls/php-coveralls
  - composer install

after_script:
  - travis_retry php vendor/bin/php-coveralls

cache:
  directories:
    - $HOME/.composer/cache/files
